# Generated by Django 5.2.17 on 2026-08-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='assigned_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
