# Generated by Django 5.2.17 on 2026-08-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=20),
        ),
    ]
