# Generated by Django 5.2.17 on 2026-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('additional', 'Additional')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
