# Generated by Django 5.2.17 on 2026-08-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_departmentnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentnotice',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
